FROM joseluzon/latex-base

RUN tlmgr update --self
RUN tlmgr install mathexam setspace adjustbox xkeyval collectbox enumitem \
    lastpage xcolor etoolbox moderncv fontawesome5 pgf multirow arydshln \
    xifthen ifmtarg gillius fontaxes moresize fontawesome wrapfig float transparent xstring raleway ly1 paracol \
    && texhash