version: "3.6"
services:
    mongodb:
        image: mongo
        container_name: mongodb
        ports: 
            - 27017:27017
        volumes: 
            - ~/.development/mongodb/dbname:/data
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=rootuser
            - MONGO_INITDB_ROOT_PASSWORD=rootpass
        networks:
            - mongodb_network

    mongo-express:
        image: mongo-express
        container_name: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
            - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
            - ME_CONFIG_MONGODB_SERVER=mongodb
        networks:
            - mongodb_network

networks:
    mongodb_network:
        driver: bridge
